### PR TITLE
Unifying Cloudy scripts with sps incident scripts

### PR DESCRIPTION
**Pull request by WillJRoper**
To ensure consistency, and importantly consistent naming and units, this PR introduces the `Parser` and `GridFile` to the cloudy scripts.

Currently an open draft to enable collaboration.

## Issue Type

- Enhancement

## Checklist
- [x] I have read the [CONTRIBUTING.md]()
- [x] I have added docstrings to all methods
- [x] I have added sufficient comments to all lines
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no pep8 errors
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by sophie-newman** [comment]
why the `hf=None`? is that just for testing?

**Comment by WillJRoper** [comment]
> why the `hf=None`? is that just for testing?

That's literally just so the script with the few changes I had made would make it past the commit checks. I've done very little so far here but opened it in draft so we can work together on it.

**Comment by sophie-newman** [comment]
I have tested this and everything is looking as expected! 

Main changes in this PR:

- Plural axis naming
- Inclusion of units. This is done in a very simple way in lines 132-149 of `create_synthesizer_grid` for a few example axes (`reference_ionisation_parameter`, `ionisation_parameter`, `metallicities`, `ages`). If an automatic way could be found, this would be preferred but it is hard to do this from the .yaml file.
- Move grid creation to `create_synthesizer_grid` rather than `create_cloudy_input_grid`
- Update parser arguments to use `--` rather than `-`

**Comment by WillJRoper** [comment]
This looks fine to me. There could be some hidden gremlins but I don't see them. The proof will be in the pudding. 

@christopherlovell I can't approve this since I made the original PR.

**Review by christopherlovell — APPROVED** [review]

**Pull request merged**
